version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comicplanner
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
